### ISSUE TITLE
Video "Scalable Applications" in not available

### ISSUE THREAD

**Issue by mfeurer** [SkafteNicki/dtu_mlops#185]
Unfortunately, I cannot access the video "Scalable Applications" from the Timeplan via [this link](https://drive.google.com/file/d/1_QLJD_yTkQmE2-_b-oMeDro1WU8KBeP3/view?usp=share_link) and I receive the following error:

![image](https://github.com/SkafteNicki/dtu_mlops/assets/5320498/156150a6-d91b-4c5a-8717-0239c2e3a604)

**Comment by SkafteNicki** [comment]
Hi @mfeurer,
Thanks for reporting this. The issue should have been solved now.
