### ISSUE TITLE
Mention pytorch-lightning's LightningCLI

### ISSUE THREAD

**Issue by mauvilsa** [SkafteNicki/dtu_mlops#79]
Given what is currently in the course, it might be worth considering to mention pytorch-lightning's [LightningCLI](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_cli.html). Already pytorch-lightning is in [M14 - Minimizing boilerplate](https://skaftenicki.github.io/dtu_mlops/s4_debugging_and_logging/M14_boilerplate.html). But `LightningCLI` could be a good complement to what is in other sections. The main goals that `LightningCLI` addresses are:

- Automatically save the full config (reproducibility)
- Separation of code from config (good practice)
- Make things automatically configurable (minimize boilerplate)

When the code is well written, i.e. parameters with type hints, descriptions in docstrings, defined where they are used ([M7 - Good coding practice](https://skaftenicki.github.io/dtu_mlops/s2_organisation_and_version_control/M7_good_coding_practice.html)), all of these parameters automatically become configurable [M10 - Config files](https://skaftenicki.github.io/dtu_mlops/s3_reproduceability/M10_config_files.html). There is no need to learn how to use another framework like Hydra.

**Comment by SkafteNicki** [comment]
Add in 6338916, thanks for the suggestion.
